✨ Add AWS VPC subnet resource
mondoohq/cnquery pull request #1827
Opened 2023-09-21 06:41 UTC by mariuskimmina

#1794

first time making changes to providers, so please review carefully. 
Example usage

![image](https://github.com/mondoohq/cnquery/assets/38843153/dea4a62d-db5d-42c4-8ce4-48f9bdbdcb23)

I wasn't sure what kind of fields to add here. Just went with `id` and `cidrs` for now - there's probably more that could make sense.

2023-09-21 14:13 UTC, mariuskimmina commented
Added the filed `mapPublicIpOnLaunch` which is the actual requirement for AWS security recommendations discussed in #1794

```
cnquery> aws.vpcs.where( arn == "arn:aws:vpc:eu-central-1:455954587013:id/vpc-091edd43468ca60e5" )[0].subnets[0].mapPublicIpOnLaunch
[ok] value: true
```

2023-09-21 16:05 UTC, tas50 commented on providers/aws/resources/aws.lr.manifest.yaml
> +      subnets: {}
```suggestion
      subnets:
        min_mondoo_version: 9.0.0
```

2023-09-21 16:05 UTC, tas50 commented on providers/aws/resources/aws.lr.manifest.yaml
> +    min_mondoo_version: latest
```suggestion
    min_mondoo_version: 9.0.0
```

2023-09-22 17:04 UTC, vjeffrey requested changes
can you please add in the subnet arn, and add an id function for the subnet `func (s *mqlAwsVpcSubnet) id() (string, error) {` that returns the arn?

this will help ensure the objects are uniquely identifiable

2023-09-23 06:56 UTC, mariuskimmina commented
I have added the arn filed, I noticed a bug tho.
Currently I have 3 subnets in AWS, the output in cnquery looks like this

aws.vpcs.where[0].subnets: [
  0: aws.vpc.subnet id="subnet-021eb62bc781a5ed5"
  1: aws.vpc.subnet id="subnet-021eb62bc781a5ed5"
  2: aws.vpc.subnet id="subnet-021eb62bc781a5ed5"
]

So the number of subnets is correct but they all have the same id.
I copied this part from the exisiting routeTables function and found that the same bug exists there as well

I have 2 route tables in my aws account

cnquery> aws.vpcs.where( arn == "arn:aws:vpc:eu-central-1:455954587013:id/vpc-091edd43468ca60e5" )[0].routeTables
aws.vpcs.where[0].routeTables: [
  0: aws.vpc.routetable id="rtb-0d28b6f55dfe767c2"
  1: aws.vpc.routetable id="rtb-0d28b6f55dfe767c2"
]

I see two route tables here but they both have the same id

2023-09-24 08:20 UTC, vjeffrey commented
did you add in the id function?
```
func (s *mqlAwsVpcSubnet) id() (string, error) {
  return s.Arn.Data, nil
}
```

route table might also need the id fix

2023-09-24 09:09 UTC, mariuskimmina commented
> did you add in the id function?
> 
> ```
> func (s *mqlAwsVpcSubnet) id() (string, error) {
>   return s.Arn.Data, nil
> }
> ```
> 
> route table might also need the id fix

Ah, adding the `id` function does seem to fix it. 

I also saw now this comment
```
to override the _id implement id()
```

But, doesn't that mean that there is probably a bug in the default _id implementation because it should have been able to use the correct `id` field for each subnet and not the same one three times?

2023-09-24 17:46 UTC, vjeffrey commented
using the arn as the id guarantees we get the unique one since it includes the region and account id - whenever dealing with aws we always want to use the arn where possible because of that.

good question about the _id thing tho, i haven't looked at it much yet in our new v9 world...i'll dig around for an answer for u on that

2023-10-01 12:32 UTC, mariuskimmina commented
Anything still needs to be done here from my side? @vjeffrey

2023-10-02 03:17 UTC, vjeffrey commented
sorry for the delay! this is great, thank you!

2023-10-02 03:17 UTC, vjeffrey approved these changes

2023-10-02 03:17 UTC, merged