Be more clear that no provider == local
mondoohq/cnquery pull request #423
Opened 2022-11-01 15:15 UTC by tas50

Right now we just say we're "using defaults" but what is the default?

Signed-off-by: Tim Smith <tsmith84@gmail.com>

2022-11-02 05:56 UTC, chris-rock requested changes

2022-11-02 05:56 UTC, chris-rock commented on apps/cnquery/cmd/builder/builder.go
> +			log.Info().Str("provider", "local").Msg("no provider specified, defaulting to local.\n  Use --help for a list of available providers.")
If we add this to the text, we need to remove `.Str("provider", "local")` otherwise we add the same information twice

2022-11-04 18:37 UTC, tas50 commented
@chris-rock it looks fine in my local version:

w/o a provider specified:
```
 ~/d/cnquery   $  /Users/tsmith/go/bin/cnquery shell
→ no provider specified, defaulting to local.
  Use --help for a list of available providers. provider=local
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
  ___ _ __   __ _ _   _  ___ _ __ _   _
 / __| '_ \ / _` | | | |/ _ \ '__| | | |
| (__| | | | (_| | |_| |  __/ |  | |_| |
 \___|_| |_|\__, |\__,_|\___|_|   \__, |
  mondoo™      |_|                |___/  interactive shell
```

2022-11-05 09:33 UTC, chris-rock commented
I update the PR to remove the property, the second line `Use --help for a list of available providers. provider=local` is confusing because you moved the info about the local provider into the first line.

2022-11-05 09:41 UTC, chris-rock approved these changes

2022-11-05 09:46 UTC, merged