🧹 simplify docs
mondoohq/cnquery pull request #497
Opened 2022-11-18 15:58 UTC by chris-rock

2022-11-21 16:03 UTC, misterpantz requested changes
Just a couple of changes, please

2022-11-21 16:03 UTC, misterpantz commented on apps/cnquery/cmd/run.go
> +	Short: "Run a MQL query",
please change this line and the next line to read "an MQL"

2022-11-22 09:32 UTC, chris-rock commented on apps/cnquery/cmd/run.go
> +	Short: "Run a MQL query",
Thank you, fixed

2022-11-22 12:30 UTC, imilchev approved these changes

2022-11-22 12:31 UTC, merged

2022-11-22 15:01 UTC, misterpantz commented on resources/packs/azure/azure_rm_web.go
> +	// NOTE: we do not return MQL resource since stacks do not have their own proper id in azure
an  MQL resource

2022-11-22 15:06 UTC, misterpantz commented on resources/packs/azure/azure_rm_web.go
> +	// NOTE: we do not return MQL resource since stacks do not have their own proper id in azure
return MQL resource --> return an MQL resource