⭐️ GCP GKE cluster resource
mondoohq/cnquery pull request #653
Opened 2022-12-21 21:46 UTC by imilchev

Signed-off-by: Ivan Milchev <ivan@mondoo.com>

2022-12-21 22:55 UTC, tas50 commented on resources/packs/gcp/gcp.lr
> +// GKE cluster resource
```suggestion
// GKE Cluster Resource
```

2022-12-22 15:22 UTC, imilchev commented on resources/packs/gcp/gcp.lr
> +// GKE cluster resource
done

2022-12-27 09:24 UTC, chris-rock requested changes
This looks great. The only thing we should do is to move the resources into the `gcp.project` scope.

2022-12-27 09:24 UTC, chris-rock commented on resources/packs/gcp/gcp.lr
> +private gcp.cluster @defaults("name") {
Cluster should be scoped in `gcp.project.cluster`. All the other resources need to be reßscoped too. I think we should also allow users to test individual clusters directly:

```
gcp.project.cluster(projectID: "myproject", name: "clustername")
```

Therefore this resource should not be private. To achieve that you need to implement the init function as done for services https://github.com/mondoohq/cnquery/blob/main/resources/packs/gcp/services.go#L99-L154

2022-12-27 10:38 UTC, imilchev commented on resources/packs/gcp/gcp.lr
> +private gcp.cluster @defaults("name") {
the rescoping is done. As agreed the init functions will be added at a later point. We will first add all the necessary GCP resources

2022-12-27 11:31 UTC, chris-rock approved these changes
Great addition @imilchev

2022-12-27 11:31 UTC, merged