⭐️ Add azure.subscription. Move all azure resources under azure.subscription
mondoohq/cnquery pull request #810
Opened 2023-01-21 08:25 UTC by preslavgerchev

Introduce a new `azure.subscription` resource:
```
cnquery> azure.subscription{name state}
azure.subscription: {
  name: "Mondoo Testing"
  state: "Enabled"
}
```

All the resources are now moved from `azure.*` to `azure.subscription.*`. This lets us build a resource hierarchy more clearly. Before:
```

cnquery> azure.compute.vms{name}
azure.compute.vms: [
  0: {
    name: "Security-Team-vm-linux-1-b9qa"
  }
  1: {
    name: "Security-Team-vm-linux-1-mjau"
  }
]
```

After:
```
cnuery> azure.subscription.compute.vms{name}
azure.subscription.compute.vms: [
  0: {
    name: "Security-Team-vm-linux-1-b9qa"
  }
  1: {
    name: "Security-Team-vm-linux-1-mjau"
  }
]
```

There are aliases introduced to keep the old resources untouched to avoid breaking changes so `azure.compute.vms` will still work

2023-01-23 08:54 UTC, chris-rock requested changes

2023-01-23 08:54 UTC, chris-rock commented on resources/packs/azure/azure.lr
> +  subscription() azure.subscription
You are shadowing the resource. It is not deterministic behaviour?

2023-01-23 08:54 UTC, chris-rock commented on resources/packs/azure/azure.lr
> +private azure.subscription.resource @defaults("id name location") {
The overlay only works if the `azure.subscription` resource has only the plural terms.

2023-01-26 23:48 UTC, imilchev commented
This does mean that when we introduce the individual assets (not sure if that's already present for Azure) you will face the following issue:
- you will be listing VMs with:
  ```
  azure.subscription.compute.vms
  ```
- you will be querying 1 VM with:
  ```
  azure.subscription.computeService.vm
  ```
If you try to change `azure.subscription.computeService.vm` to `azure.subscription.compute.vm` it will result in an MQL runtime error. I have the same problem for GCP resources. Still need to look into how to make MQL work with both `azure.subscription.compute.vms()` and `azure.subscription.compute.vm`

2023-02-07 12:02 UTC, imilchev approved these changes
Looks similar to what we have for GCP

2023-02-07 14:45 UTC, chris-rock approved these changes
Thank you @preslavgerchev

2023-02-08 16:42 UTC, merged